config/routes.rb
Rails.application.routes.draw do

  root 'top#index'

  resources :posts do
    collection do
      get :scrape
      get :rewrite
    end
  end

  resources :sites do
    collection do
      get :sync
    end
  end

end

app/models/site.rb
class Site < ActiveRecord::Base
  include GoogleSpreadsheets::Enhanced::Syncing
  sync_with :site_rows, spreadsheet_id: '0ArhV7gTgs6Z8dFNLVVVwdE1Kd3FLWWJXZlRweGdEcFE'
  after_commit :sync_site_row

  has_many :posts
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => ENV["BASIC_KEY"], :password => ENV["BASIC_PW"] if Rails.env.production?
  respond_to :html, :json

  def index
    @sites = Site.order(:created_at).page params[:page]
    respond_with(@sites)
  end

  def sync
    Site.sync_with_site_rows
    @sites = Site.all
    respond_to do |format|
      format.json { render :json => @sites }
    end
  end

  def show
    respond_with(@site)
  end

  def new
    @site = Site.new
    respond_with(@site)
  end

  def edit
  end

  def create
    @site = Site.new(site_params)
    @site.save
    respond_with(@site)
  end

  def update
    @site.update(site_params)
    respond_with(@site)
  end

  def destroy
    @site.destroy
    respond_with(@site)
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:name, :url, :rss, :active)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.haml
= form_for @site do |f|
  - if @site.errors.any?
    #error_explanation
      %h2= "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      %ul
        - @site.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_area :name, {class: 'text'}
  .field
    = f.label :url
    = f.text_area :url, {class: 'text'}
  .field
    = f.label :rss
    = f.text_area :rss, {class: 'text'}
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/sites/edit.html.haml
- @body_class = 'admin scaffold'

%h1 Editing site

= render 'form'

= link_to 'Show', @site
\|
= link_to 'Back', sites_path

app/views/sites/index.html.haml
- @body_class = 'admin scaffold'

:javascript
  $(function() {

    //jquery ajax
    $('.js-sync-ajax').on('click', function(e) {
      e.preventDefault();
      getJson($(e.currentTarget));
    });
    function getJson($el) {
      if($el.hasClass('is-loading')) return;

      var url = $el.attr('href') + '/' + $el.attr('action');
      $el.addClass('is-loading');
      $.ajax({
        url: url,
        type: 'GET',
        dataType: 'json'
      })
      .done(function(e) {
        console.log("success:", e, e[0]);
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        $el.removeClass('is-loading');
      });
    }

  });

%h1 Listing sites

= link_to sites_path, action: :sync, class: 'button js-sync-ajax' do
  sync spredsheets

%table
  %tr
    %th Name
    %th Url,Rss
    %th Active
    %th
    %th
    %th

  - @sites.each do |site|
    %tr
      %td= site.name
      %td
        = site.url
        %br
        = site.rss
      %td= site.active
      %td= link_to 'Show', site
      %td= link_to 'Edit', edit_site_path(site)
      %td= link_to 'Destroy', site, :method => :delete, :data => { :confirm => 'Are you sure?' }

= paginate @sites

%br

= link_to 'New Site', new_site_path

app/views/sites/new.html.haml
- @body_class = 'admin scaffold'

%h1 New site

= render 'form'

= link_to 'Back', sites_path

app/views/sites/show.html.haml
- @body_class = 'admin scaffold'

%p#notice= notice

%p
  %b Name:
  = @site.name
%p
  %b Url:
  = @site.url
%p
  %b Rss:
  = @site.rss
%p
  %b Active:
  = @site.active
%p
  %b Posts:
  %ul
    - @site.posts.each do |i|
      %li
        = i.id

= link_to 'Edit', edit_site_path(@site)
\|
= link_to 'Back', sites_path

app/views/sites/sync.html.haml
sync